- hosts: localhost
  connection: local
  become: true
  tasks:
    - name: Change permissions of sl
      ansible.builtin.file:
        dest: /usr/bin/sl
        mode: '0700'

    - name:  Change permissions of VLC
      ansible.builtin.file:
        dest: /usr/bin/vlc
        mode: '0700'
